replicaCount: 1

imagePullSecrets:
  - name: 

image:
  repository: myapp
  tag: latest
  pullPolicy: IfNotPresent

fluentd:
  image:
    repository: fluent/fluentd
    tag: v1.12.0
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
