name: deploy-app

on:
  workflow_dispatch

env:
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}        
  CLUSTER_NAME: ${{ vars.AZURE_CLUSTER_NAME }}
  PROD_REGISTRY: ${{ vars.PROD_REGISTRY }}
  PROD_APP_IMAGE_REPO: ${{ vars.PROD_APP_IMAGE_REPO }}
  PROD_APP_IMAGE_TAG: ${{ vars.PROD_APP_IMAGE_TAG }}
  PROD_UTILITY_IMAGE_REPO: ${{ vars.PROD_UTILITY_IMAGE_REPO }}
  PROD_UTILITY_IMAGE_TAG: ${{ vars.PROD_UTILITY_IMAGE_TAG }}

jobs:
  deploy-myapp-to-k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Gets K8s context
      uses: azure/aks-set-context@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
      id: login

    - name: Bake helm charts
      uses: azure/k8s-bake@v1
      with:
        renderEngine: helm
        helmChart: ./charts/myapp
        overrides: |
          image.repository=${{ env.PROD_REGISTRY }}/${{ env.PROD_APP_IMAGE_REPO }}
          image.tag=${{ evn.PROD_APP_IMAGE_TAG }}
          fluentd.image.repository=${{ env.PROD_REGISTRY }}/${{ env.PROD_UTILITY_IMAGE_REPO }}
          fluentd.image.tag=${{ evn.PROD_UTILITY_IMAGE_TAG }}
      id: bake
